const aeroportos = [
  { name: "ALMEIRIM", iata: "GGF" },
  { name: "ALTA FLORESTA", iata: "AFL" },
  { name: "ALTAMIRA", iata: "ATM" },
  { name: "ANGRA DOS REIS", iata: "GDR" },
  { name: "ARACAJU", iata: "AJU" },
  { name: "ARACATI", iata: "ARX" },
  { name: "ARAGUAINA", iata: "AUX" },
  { name: "ARAÇATUBA", iata: "ARU" },
  { name: "ARIPUANA", iata: "AIR" },
  { name: "ÁGUA BOA", iata: "GGB" },
  { name: "BARCELOS", iata: "BAZ" },
  { name: "BARRA DO GARCAS", iata: "BPG" },
  { name: "BARREIRAS", iata: "BRA" },
  { name: "BARREIRINHAS", iata: "BRB" },
  { name: "BARRETOS", iata: "BAT" },
  { name: "BAURU", iata: "JTC" },
  { name: "BELO HORIZONTE - CONFINS", iata: "CNF" },
  { name: "BELO HORIZONTE - PAMPULHA", iata: "PLU" },
  { name: "BELÉM", iata: "BEL" },
  { name: "BOA VISTA", iata: "BVB" },
  { name: "BOIPEBA", iata: "PBA" },
  { name: "BONITO", iata: "BYO" },
  { name: "BRASÍLIA", iata: "BSB" },
  { name: "BREVES", iata: "BVS" },
  { name: "BÚZIOS", iata: "BZC" },
  { name: "BÚZIOS", iata: "BZS" },
  { name: "CABO FRIO", iata: "CFB" },
  { name: "CACOAL", iata: "OAL" },
  { name: "CALDAS NOVAS", iata: "CLV" },
  { name: "CAMPINA GRANDE", iata: "CPV" },
  { name: "CAMPO GRANDE", iata: "CGR" },
  { name: "CAMPOS DOS GOITACAZES", iata: "CAW" },
  { name: "CARAUARI", iata: "CAF" },
  { name: "CARUARU", iata: "CAU" },
  { name: "CASCAVEL", iata: "CAC" },
  { name: "CAXIAS DO SUL", iata: "CXJ" },
  { name: "CHAPECÓ", iata: "XAP" },
  { name: "COARI", iata: "CIZ" },
  { name: "CONFRESA", iata: "CFO" },
  { name: "CORREIA PINTO-LAGES-REGIONAL PLANALTO SERRANO", iata: "EEA" },
  { name: "CORUMBA", iata: "CMG" },
  { name: "CRATEÚS", iata: "QXX" },
  { name: "CRUZEIRO DO SUL", iata: "CZS" },
  { name: "CUIABÁ", iata: "CGB" },
  { name: "CURITIBA", iata: "CWB" },
  { name: "DOURADOS", iata: "DOU" },
  { name: "EIRUNEPÉ", iata: "ERN" },
  { name: "FERNANDO DE NORONHA", iata: "FEN" },
  { name: "FLORIANÓPOLIS", iata: "FLN" },
  { name: "FORTALEZA", iata: "FOR" },
  { name: "FOZ DO IGUAÇU", iata: "IGU" },
  { name: "FRANCA", iata: "FRC" },
  { name: "GOIÂNIA", iata: "GYN" },
  { name: "GOVERNADOR VALADARES", iata: "GVR" },
  { name: "IGUATU", iata: "QIG" },
  { name: "ILHÉUS", iata: "IOS" },
  { name: "IMPERATRIZ", iata: "IMP" },
  { name: "IPATINGA / VALE DO AÇO", iata: "IPN" },
  { name: "ITAITUBA", iata: "ITB" },
  { name: "JAGUARUNA-CRICIÚMA", iata: "JJG" },
  { name: "JERICOACOARA", iata: "JJD" },
  { name: "JI PARANA", iata: "JPR" },
  { name: "JOINVILLE", iata: "JOI" },
  { name: "JOÃO PESSOA", iata: "JPA" },
  { name: "JUAZEIRO DO NORTE", iata: "JDO" },
  { name: "JUIZ DE FORA", iata: "JDF" },
  { name: "JUIZ DE FORA -ZONA DA MATA", iata: "IZA" },
  { name: "JUNDIAI", iata: "QDV" },
  { name: "JURUTI", iata: "JRT" },
  { name: "JUÍNA", iata: "JIA" },
  { name: "LENÇÓIS/CHAPADA DIAMANTINA", iata: "LEC" },
  { name: "LONDRINA", iata: "LDB" },
  { name: "LÁBREA", iata: "LBR" },
  { name: "MACAPÁ", iata: "MCP" },
  { name: "MACAÉ", iata: "MEA" },
  { name: "MACEIÓ", iata: "MCZ" },
  { name: "MANAUS", iata: "MAO" },
  { name: "MARABÁ", iata: "MAB" },
  { name: "MARILIA", iata: "MII" },
  { name: "MARINGÁ", iata: "MGF" },
  { name: "MAUES", iata: "MBZ" },
  { name: "MONTE ALEGRE", iata: "MTE" },
  { name: "MONTE DOURADO", iata: "MEU" },
  { name: "MONTES CLAROS", iata: "MOC" },
  { name: "MORRO DE SÃO PAULO", iata: "MXQ" },
  { name: "MOSSORO", iata: "MVF" },
  { name: "MUCUGÊ", iata: "CHD" },
  { name: "NATAL", iata: "NAT" },
  { name: "NAVEGANTES – BALNEÁRIO CAMBORIÚ – BLUMENAU", iata: "NVT" },
  { name: "OBIDOS", iata: "OBI" },
  { name: "ORIXIMINA", iata: "ORX" },
  { name: "PALMAS", iata: "PMW" },
  { name: "PARAUAPEBAS", iata: "CKS" },
  { name: "PARINTINS", iata: "PIN" },
  { name: "PARNAIBA", iata: "PHB" },
  { name: "PASSO FUNDO", iata: "PFB" },
  { name: "PAULO AFONSO", iata: "PAV" },
  { name: "PELOTAS", iata: "PET" },
  { name: "PENÍNSULA DE MARAÚ", iata: "BGS" },
  { name: "PETROLINA", iata: "PNZ" },
  { name: "PONTA GROSSA", iata: "PGZ" },
  { name: "PORTO ALEGRE", iata: "POA" },
  { name: "PORTO SEGURO", iata: "BPS" },
  { name: "PORTO TROMBETAS", iata: "TMT" },
  { name: "PORTO VELHO", iata: "PVH" },
  { name: "PRESIDENTE PRUDENTE", iata: "PPB" },
  { name: "RECIFE", iata: "REC" },
  { name: "RIBEIRÃO PRETO", iata: "RAO" },
  { name: "RIO BRANCO", iata: "RBR" },
  { name: "RIO DE JANEIRO - GALEÃO", iata: "GIG" },
  { name: "RIO DE JANEIRO - SANTOS DUMONT", iata: "SDU" },
  { name: "RIO GRANDE", iata: "RIG" },
  { name: "RIO VERDE", iata: "RVD" },
  { name: "RONDONOPOLIS", iata: "ROO" },
  { name: "SALVADOR", iata: "SSA" },
  { name: "SANTA ISABEL DO RIO NEGRO", iata: "IRZ" },
  { name: "SANTA MARIA", iata: "RIA" },
  { name: "SANTA ROSA", iata: "SRA" },
  { name: "SANTAREM", iata: "STM" },
  { name: "SANTO ÂNGELO", iata: "GEL" },
  { name: "SERRA TALHADA", iata: "SET" },
  { name: "SINOP", iata: "OPS" },
  { name: "SOBRAL", iata: "QBX" },
  { name: "SORRISO", iata: "SMT" },
  { name: "SÃO BENEDITO", iata: "QXY" },
  { name: "SÃO BORJA", iata: "JBS" },
  { name: "SÃO FÉLIX DO ARAGUAIA", iata: "SXO" },
  { name: "SÃO GABRIEL DA CACHOEIRA", iata: "SJL" },
  { name: "SÃO JOSÉ DO RIO PRETO", iata: "SJP" },
  { name: "SÃO JOSÉ DOS CAMPOS", iata: "SJK" },
  { name: "SÃO LUIS", iata: "SLZ" },
  { name: "SÃO PAULO - CAMPINAS", iata: "VCP" },
  { name: "SÃO PAULO - CONGONHAS", iata: "CNG" },
  { name: "SÃO PAULO - GUARULHOS", iata: "GRU" },
  { name: "TABATINGA", iata: "TBT" },
  { name: "TANGARÁ DA SERRA", iata: "TGQ" },
  { name: "TAUÁ", iata: "QTA" },
  { name: "TEFÉ", iata: "TFF" },
  { name: "TEIXEIRA DE FREITAS", iata: "TXF" },
  { name: "TERESINA", iata: "THE" },
  { name: "TRES LAGOAS", iata: "TJL" },
  { name: "UBERABA", iata: "UBA" },
  { name: "UBERLANDIA", iata: "UDI" },
  { name: "UNA-COMANDATUBA", iata: "UNA" },
  { name: "UNIÃO DA VITÓRIA", iata: "UVI" },
  { name: "URUGUAIANA", iata: "URG" },
  { name: "VILHENA", iata: "BVH" },
  { name: "VITÓRIA", iata: "VIX" },
  { name: "VITÓRIA DA CONQUISTA", iata: "VDC" },
];

export default aeroportos;
